nexus:
  image: sonatype/nexus
  ports:
  - 8081:8081
  volumes:
  - /etc/nexus-data:/sonatype-work
registry:
  image: registry
  ports:
  - ${DOCKERREGISTRY_PORT}:5000
  volumes:
  - /etc/docker-registry:/var/lib/registry
registry-ui:
  image: atcol/docker-registry-ui
  ports:
  - 8080:8080
  environment:
  - REG1="http://${DOCKER_HOST_IP_INFRA}:${DOCKERREGISTRY_PORT}/v1/"
sonarqube:
  image: sonarqube:5.1
  ports:
  - 9000:9000
  - 9092:9092
sonar-db:
  image: postgres
  environment:
  - POSTGRES_USER=sonar
  - POSTGRES_PASSWORD=sonar
  volumes:
  - /etc/postgres/sonar/data:/var/lib/postgresql/data