nexus:
  image: sonatype/nexus
  net: "infrastructure"
  ports:
  - 8081:8081
  volumes:
  - /etc/nexus-data:/sonatype-work

registry:
  image: registry
  net: "infrastructure"
  ports:
  - 5000:5000
  volumes:
  - /etc/docker-registry:/var/lib/registry
registry-ui:
  image: atcol/docker-registry-ui
  net: "infrastructure"
  ports:
  - 8080:8080
  environment:
  - REG1=http://registry:5000/v1/
sonarqube:
  image: sonarqube:5.1
  net: "infrastructure"
  ports:
  - 9000:9000
  - 5432:5432
  environment:
  - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar
  log_driver: "syslog"
sonar-db:
  image: postgres
  net: "infrastructure"
  net: container:sonarqube
  environment:
  - POSTGRES_USER=sonar
  - POSTGRES_PASSWORD=sonar
  volumes:
  - /etc/postgres/sonar/data:/var/lib/postgresql/data
  